name: deploy
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Installs Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      - name: Build
        run: npm run build
      - name: zip dist
        run: zip -r terraform/function.zip dist
      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
